Weather app using API
NiiazalyDzhumaliev/weatherApp pull request #1
Opened 2020-10-22 09:39 UTC by NiiazalyDzhumaliev

The project was created using API:

- fetch data;
- async/await;
- code refactored into modules;
- basic styling using Bootstrap.

2020-10-22 09:57 UTC, christianotieno requested changes
### Changes Required ♻️ 
Hello @NiiazalyDzhumaliev 👋 
You have done a good job so far. Keep it up. 👏 
Kindly take care of the following highlighted issues before we proceed. 👇 

### Happy coding 💻 

#### Christian Otieno (TSE)

2020-10-22 09:57 UTC, christianotieno commented on README.md
> +
## Add a live link to the page

- [ ] Add a live link to where the page is live. let's make sure the README is more descriptive. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-10-22 09:57 UTC, christianotieno commented on package.json
>    }
## Webpack configuration

- [ ] All webpack related packages should be included in `package.json` like `webpack`, `webpack-cli`, `webpack-dev-server` etc. Also, those packages should be added as **devDependencies.** We are currently missing some of these in this file, let's add them. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/devdep_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))

- [ ] We need to have necessary run common commands like `build`, `development` to be present in `package.json` inside \`scripts'. Here is a basic example we can draw inspiration from 👇 ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))

```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

2020-10-22 10:28 UTC, NiiazalyDzhumaliev commented
Thanks for the reasonable comments.

- add a live version of the app;
- add the related packages;
- add scripts.

2020-10-22 10:33 UTC, rOluochKe requested changes
Hello @NiiazalyDzhumaliev 
### You have done well so far :clap: However, you have one issue to fix:-
- [ ] Add a toggle button to determine if the result will be shown in Celsius or Fahrenheit
### Make the change and submit for another code review. Good luck.
- Happy coding!

2020-10-22 10:41 UTC, rOluochKe requested changes
### Make the changes from the previous review and submit for another code review.

2020-10-23 10:48 UTC, NiiazalyDzhumaliev commented
Add toggle button to switch degree measures.

2020-10-23 10:56 UTC, whiz25 approved these changes
## Approved :clap: 
Nice work addressing the changes requested. Merge and proceed to the next project.


### Martin Afani

2020-11-20 08:02 UTC, merged